apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-test-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: java-test-app-pods
        color: blue
    spec:
      containers:
      - name: java-test-app-container
        image: java-test-app:v1
        ports:
        - containerPort: 80