apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-test-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: java-test-app-pods
        color: blue
    spec:
      containers:
      - name: java-test-app-container
        image: nerdondon/java-test-app:v1
        env:
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 80