apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-test-app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: dotnet-test-app-pods
        color: blue
    spec:
      containers:
      - name: dotnet-test-app-container
        image: dotnet-test-app:v1
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        ports:
        - containerPort: 80