apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dotnet-test-app-blue
spec:
  replicas: 7
  template:
    metadata:
      labels:
        name: dotnet-test-app-pods-bg
        color: blue
    spec:
      containers:
      - name: dotnet-test-app-container
        image: nerdondon/dotnet-test-app:v1
        resources:
          limits:
            cpu: 700m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: POD_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 80
        imagePullPolicy: Always