apiVersion: v1
kind: Service
metadata:
    name: dotnet-test-app-bg
spec:
    type: LoadBalancer
    selector:
        name: dotnet-test-app-pods-bg
        color: blue
    ports:
    - port: 80
      targetPort: 80